repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes]
        name: mypy check
        files: meta_learn_bo
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8 check
        files: meta_learn_bo/
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 for test files
        files: test/
